FROM golang:1.26 AS builder
WORKDIR /app
COPY pkg ./pkg
COPY services/product/go.mod services/product/go.sum ./services/product/

WORKDIR /app/services/product
RUN go mod download

WORKDIR /app
COPY services/product ./services/product

WORKDIR /app/services/product
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/product ./cmd

FROM alpine:latest
COPY --from=builder /app/product /product
CMD ["/product"]