services:
  redis:
    image: redis:8.6.5-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - ":6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres-products:
    image: postgres:15-alpine
    container_name: postgres-products
    env_file:
      - .env
    ports:
      - ":5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/product/init.sh:/docker-entrypoint-initdb.d/init.sh

  product-migrations:
    container_name: product-migrations
    image: apigateway:1.0
    command: ["/product", "-cmd=up"]
    env_file:
      - .env
    depends_on:
      postgres-products:
        condition: service_healthy

  product-service:
    container_name: product-service
    image: apigateway:1.0
    depends_on:
      postgres-products:
        condition: service_healthy
      product-migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    command: ./product

  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    env_file:
      - .env
    ports:
      - ":5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/user/init.sh:/docker-entrypoint-initdb.d/init.sh
  
  user-migrations:
    container_name: user-migrations
    image: apigateway:1.0
    command: ["/user", "-cmd=up"]
    env_file:
      - .env
    depends_on:
      postgres-users:
        condition: service_healthy

  user-service:
    container_name: user-service
    image: apigateway:1.0
    depends_on:
      postgres-users:
        condition: service_healthy
      user-migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "${USER_PORT}:${USER_PORT}"
    command: ./user

  postgres-orders:
    image: postgres:15-alpine
    container_name: postgres-orders
    env_file:
      - .env
    ports:
      - ":5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/order/init.sh:/docker-entrypoint-initdb.d/init.sh

  order-service:
    container_name: order-service
    image: apigateway:1.0
    depends_on:
      postgres-orders:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${ORDER_PORT}:${ORDER_PORT}"
    command: ./order