services:
  postgres-products:
    image: postgres:15-alpine
    container_name: postgres-products
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=products_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  product-tests:
    container_name: product-tests
    build:
      context: .
      dockerfile: Dockerfile.product.tests
    depends_on:
      postgres-products:
        condition: service_healthy
    environment:
      - PRODUCT_POSTGRES_DB_USER=postgres
      - PRODUCT_POSTGRES_DB_PASSWORD=test
      - PRODUCT_DB_HOST=postgres-products
      - PRODUCT_DB_PORT=5432
      - PRODUCT_DB_NAME=products_db
    command: go test -v -cover ./internal/handler/... ./internal/service/... ./internal/repository/...

  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=users_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  user-tests:
    container_name: user-tests
    build:
      context: .
      dockerfile: Dockerfile.user.tests
    depends_on:
      postgres-users:
        condition: service_healthy
    environment:
      - USER_POSTGRES_DB_USER=postgres
      - USER_POSTGRES_DB_PASSWORD=test
      - USER_DB_HOST=postgres-users
      - USER_DB_PORT=5432
      - USER_DB_NAME=users_db
    command: go test -v -cover ./internal/handler/... ./internal/service/... ./internal/repository/...