FROM golang:1.26 AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY services/product services/product

RUN go mod download
RUN go build -o product ./services/product/cmd

FROM alpine:latest
COPY --from=builder /app/product /product
CMD ["/product"]