FROM golang:1.26 AS builder
WORKDIR /app
COPY pkg ./pkg
COPY services/user/go.mod services/user/go.sum ./services/user/

WORKDIR /app/services/user
RUN go mod download

WORKDIR /app
COPY services/user ./services/user

WORKDIR /app/services/user
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/user ./cmd

FROM alpine:latest
COPY --from=builder /app/user /user
CMD ["/user"]