FROM golang:1.26
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o product ./services/product/cmd

FROM alpine:latest
COPY --from=builder /app/product /product
CMD ["/product"]

