#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${PRODUCT_MIGRATION_DB_USER} WITH PASSWORD '${PRODUCT_MIGRATION_DB_PASSWORD}';
    CREATE USER ${PRODUCT_DB_USER} WITH PASSWORD '${PRODUCT_DB_PASSWORD}';

    GRANT ALL PRIVILEGES ON SCHEMA public TO ${PRODUCT_MIGRATION_DB_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${PRODUCT_MIGRATION_DB_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${PRODUCT_MIGRATION_DB_USER};

    GRANT USAGE ON SCHEMA public TO ${PRODUCT_DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${PRODUCT_MIGRATION_DB_USER} IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PRODUCT_DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${PRODUCT_MIGRATION_DB_USER} IN SCHEMA public 
    GRANT USAGE, SELECT ON SEQUENCES TO ${PRODUCT_DB_USER};
EOSQL