#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${USER_MIGRATION_DB_USER} WITH PASSWORD '${USER_MIGRATION_DB_PASSWORD}';
    CREATE USER ${USER_DB_USER} WITH PASSWORD '${USER_DB_PASSWORD}';

    GRANT ALL PRIVILEGES ON SCHEMA public TO ${USER_MIGRATION_DB_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${USER_MIGRATION_DB_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${USER_MIGRATION_DB_USER};

    GRANT USAGE ON SCHEMA public TO ${USER_DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${USER_MIGRATION_DB_USER} IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${USER_DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${USER_MIGRATION_DB_USER} IN SCHEMA public 
    GRANT USAGE, SELECT ON SEQUENCES TO ${USER_DB_USER};
EOSQL
