#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${ORDER_MIGRATION_DB_USER} WITH PASSWORD '${ORDER_MIGRATION_DB_PASSWORD}';
    CREATE USER ${ORDER_DB_USER} WITH PASSWORD '${ORDER_DB_PASSWORD}';

    GRANT ALL PRIVILEGES ON SCHEMA public TO ${ORDER_MIGRATION_DB_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${ORDER_MIGRATION_DB_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${ORDER_MIGRATION_DB_USER};

    GRANT USAGE ON SCHEMA public TO ${ORDER_DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${ORDER_MIGRATION_DB_USER} IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${ORDER_DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${ORDER_MIGRATION_DB_USER} IN SCHEMA public 
    GRANT USAGE, SELECT ON SEQUENCES TO ${ORDER_DB_USER};
EOSQL
